### ISSUE TITLE
App crashes if something is wrong with hardware

### ISSUE THREAD

**Issue by EvilLord666** [Wissance/Zerial#11]
should solve and make it less susceptible to hardware malfunction

**Comment by EvilLord666** [comment]
seems it was fixed here:
```
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Wissance.Zerial.Desktop.ViewModels.MainWindowViewModel.OnSerialDeviceDataReceived(Object sender, SerialDataReceivedEventArgs e) in E:\Projects\Wissance\Zerial\app\Wissance.Zerial\Wissance.Zerial.Desktop\ViewModels\MainWindowViewModel.cs:line 246
   at System.IO.Ports.SerialPort.CatchReceivedEvents(Object src, SerialDataReceivedEventArgs e)
   at System.IO.Ports.SerialStream.EventLoopRunner.CallReceiveEvents(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```
